### ISSUE TITLE
Object.defineproperty vs proxy

### ISSUE THREAD

**Issue by aafnnp** [raghav-misra/senko#4]
why not use proxy?

**Comment by raghav-misra** [comment]
I considered this myself, but proxy support is rather sus afaik.

Also the way the library works with `useState` calls internally, a proxy may not be the best idea.

Last thing, I think the main advantage that proxies bring, dynamically adding properties to the object, is not the most useful concept here because for better structure and Typescript support, the library's user would have all the properties predefined, 99% percent of the time.

Thx for taking an interest in the project btw,
Raghav
